/* Copyright (C) 2005-2022, UNIGINE. All rights reserved.
 *
 * This file is a part of the UNIGINE 2 SDK.
 *
 * Your use and / or redistribution of this software in source and / or
 * binary form, with or without modification, is subject to: (i) your
 * ongoing acceptance of and compliance with the terms and conditions of
 * the UNIGINE License Agreement; and (ii) your inclusion of this notice
 * in any version of this software that you use or redistribute.
 * A copy of the UNIGINE License Agreement is available by contacting
 * UNIGINE. at http://unigine.com/
 */

// DO NOT EDIT DIRECTLY. This is an auto-generated file. Your changes will be lost.
#pragma once
#include "UnigineAsyncQueue.h"
#include "UnigineBase.h"
#include "UnigineBiMap.h"
#include "UnigineCallback.h"
#include "UnigineCamera.h"
#include "UnigineChecksum.h"
#include "UnigineComponentSystem.h"
#include "UnigineCompress.h"
#include "UnigineConfig.h"
#include "UnigineConsole.h"
#include "UnigineControls.h"
#include "UnigineCurve2d.h"
#include "UnigineDecals.h"
#include "UnigineDir.h"
#include "UnigineDisplays.h"
#include "UnigineEditor.h"
#include "UnigineEllipsoid.h"
#include "UnigineEngine.h"
#include "UnigineExport.h"
#include "UnigineFactory.h"
#include "UnigineFfp.h"
#include "UnigineFields.h"
#include "UnigineFileSystem.h"
#include "UnigineFunction.h"
#include "UnigineGUID.h"
#include "UnigineGame.h"
#include "UnigineGeodetics.h"
#include "UnigineGeodeticsTransformer.h"
#include "UnigineGui.h"
#include "UnigineHash.h"
#include "UnigineHashMap.h"
#include "UnigineHashSet.h"
#include "UnigineImage.h"
#include "UnigineImport.h"
#include "UnigineInput.h"
#include "UnigineInterface.h"
#include "UnigineInterpreter.h"
#include "UnigineJson.h"
#include "UnigineLights.h"
#include "UnigineLoadingScreen.h"
#include "UnigineLog.h"
#include "UnigineLogic.h"
#include "UnigineMap.h"
#include "UnigineMaterial.h"
#include "UnigineMaterials.h"
#include "UnigineMathLib.h"
#include "UnigineMathLib2d.h"
#include "UnigineMathLibBVec4.h"
#include "UnigineMathLibBounds.h"
#include "UnigineMathLibCommon.h"
#include "UnigineMathLibConcave.h"
#include "UnigineMathLibConvex.h"
#include "UnigineMathLibDMat4.h"
#include "UnigineMathLibDVec2.h"
#include "UnigineMathLibDVec3.h"
#include "UnigineMathLibDVec4.h"
#include "UnigineMathLibGeometry.h"
#include "UnigineMathLibHVec2.h"
#include "UnigineMathLibHVec3.h"
#include "UnigineMathLibHVec4.h"
#include "UnigineMathLibIVec2.h"
#include "UnigineMathLibIVec3.h"
#include "UnigineMathLibIVec4.h"
#include "UnigineMathLibMat2.h"
#include "UnigineMathLibMat3.h"
#include "UnigineMathLibMat4.h"
#include "UnigineMathLibNoise.h"
#include "UnigineMathLibNumerical.h"
#include "UnigineMathLibPolygon.h"
#include "UnigineMathLibQuat.h"
#include "UnigineMathLibRandom.h"
#include "UnigineMathLibSHBasis.h"
#include "UnigineMathLibSVec4.h"
#include "UnigineMathLibSimd.h"
#include "UnigineMathLibVec2.h"
#include "UnigineMathLibVec3.h"
#include "UnigineMathLibVec4.h"
#include "UnigineMemory.h"
#include "UnigineMesh.h"
#include "UnigineMeshDynamic.h"
#include "UnigineMeshStatic.h"
#include "UnigineNode.h"
#include "UnigineNodes.h"
#include "UnigineObjects.h"
#include "UniginePackageUng.h"
#include "UniginePair.h"
#include "UniginePalette.h"
#include "UniginePath.h"
#include "UniginePathFinding.h"
#include "UniginePhysicals.h"
#include "UniginePhysics.h"
#include "UniginePlayers.h"
#include "UniginePlugin.h"
#include "UniginePool.h"
#include "UniginePrimitives.h"
#include "UnigineProfiler.h"
#include "UnigineProperties.h"
#include "UniginePtr.h"
#include "UnigineRegExp.h"
#include "UnigineRender.h"
#include "UnigineResource.h"
#include "UnigineSet.h"
#include "UnigineShader.h"
#include "UnigineSignal.h"
#include "UnigineSort.h"
#include "UnigineSounds.h"
#include "UnigineSplineGraph.h"
#include "UnigineStack.h"
#include "UnigineStreams.h"
#include "UnigineString.h"
#include "UnigineSystemInfo.h"
#include "UnigineTextures.h"
#include "UnigineThread.h"
#include "UnigineTileset.h"
#include "UnigineTilesetFile.h"
#include "UnigineTimer.h"
#include "UnigineTree.h"
#include "UnigineType.h"
#include "UnigineUlon.h"
#include "UnigineUserInterface.h"
#include "UnigineUtils.h"
#include "UnigineVector.h"
#include "UnigineVersion.h"
#include "UnigineViewport.h"
#include "UnigineVisualizer.h"
#include "UnigineWidgets.h"
#include "UnigineWindowManager.h"
#include "UnigineWorld.h"
#include "UnigineWorlds.h"
#include "UnigineXml.h"
